config/routes.rb
Rails.application.routes.draw do
  # resources :authors
  resources :authors, only: [:index, :show] do
    resources :books, only: [:index, :show, :new, :edit]
  end

  resources :books, only: [:index, :show, :new, :create, :edit, :update]

  root 'authors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:author_id]
      @author = Author.find_by(id: params[:author_id])
      if @author
        @books = @author.books
      else
        redirect_to books_path
      end
    else
      @books = Book.all
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    if params[:author_id] && !Author.exists?(params[:author_id])
      redirect_to authors_path, alert: "Author not found."
    else
      @book = Book.new(author_id: params[:author_id])
    end
  end

  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to book_path(@book)
  end

  def edit
    if params[:author_id]
      author = Author.find_by(id: params[:author_id])
      if author.nil?
        redirect_to authors_path, alert: "Author not found."
      else
        @book = author.books.find_by(id: params[:id])
        redirect_to author_books_path(author), alert: "Book not found." if @book.nil?
      end
    else
      @book = Book.find(params[:id])
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to book_path(@book)
  end

  private

  def book_params
    params.require(:book).permit(:title, :author_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def author_id_field(book)
    if book.author.nil?
      select_tag "book[author_id]", options_from_collection_for_select(Author.all, :id, :name)
    else
      hidden_field_tag "book[author_id]", book.author_id
    end
  end
end

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

app/views/authors/index.html.erb
<h1>Authors</h1>
<% if flash[:alert] %>
  <div id="alert">
    <%= flash[:alert] %> 
  </div>
<% end %>
<ul>
  <% @authors.each do |author| %>
    <li><%= link_to author.name, author_path(author.id) %></li>
  <% end %>
</ul>

app/views/authors/new.html.erb
<h1>Authors#new</h1>
<p>Find me in app/views/authors/new.html.erb</p>

app/views/authors/show.html.erb
<h1>Author</h1>

<h4>Name: <%= @author.name %></h4>
<p>Number of books written: <%= @author.books.count %></p>
<hr>
<h4><%= link_to 'Books', author_books_path(@author.id) %></h4>
<ul>
  <% @author.books.each do |book| %>
    <li><%= book.title %></li>
  <% end %>
</ul>
<hr>
<p>
  <%= link_to 'Add a new book', new_author_book_path(@author) %>
</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  
  <%= author_id_field(@book) %><br>

  <%= f.submit %>
<% end %>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/edit.html.erb
<h1>Edit a Book</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<h1>Books</h1>
<% if flash[:alert] %>
  <div id="alert">
    <%= flash[:alert] %> 
  </div>
<% end %>
<ul>
  <% @books.each do |book| %>
    <li><%= link_to book.title, author_book_path(book.author.id, book.id) %></li>
  <% end %>
</ul>
<hr>
<p>
  <%= link_to "Add a new book", new_book_path %>
</p>

app/views/books/new.html.erb
<h1>Add a new book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<h1>Book</h1>

<p>Title: <%= @book.title %></p>

<p>Author: <%= link_to @book.author.name, author_path(@book.author) if @book.author %> (<%= link_to "Edit Book", edit_author_book_path(@book.author, @book) if @book.author %>)</p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedRoutes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>